# Verwenden eines passenden Basis-Images mit H2-Datenbank
FROM openjdk:17-jdk-alpine
WORKDIR /h2

COPY ./h2-2.2.224.jar /h2/h2.jar
COPY ./testdb /h2/testdb
COPY src/main/resources/data.sql /h2/data.sql
COPY src/main/resources/schema.sql /h2/schema.sql

EXPOSE 9092
CMD if [ ! -f /h2/testdb/.initialized ]; then \
      java -cp h2.jar org.h2.tools.RunScript -url jdbc:h2:./testdb -user user -password password -script schema.sql && \
      java -cp h2.jar org.h2.tools.RunScript -url jdbc:h2:./testdb -user user -password password -script data.sql && \
      touch /h2/testdb/.initialized; \
    fi && \
    java -cp h2.jar org.h2.tools.Server -tcp -tcpAllowOthers -web -webAllowOthers -ifNotExists