INSERT INTO ALBUM (ID_ALBUM, ARTIST, NAME, TITLE_TRACK)
VALUES(1, 'The Boyz', 'Phantasy Pt. 3', 'Nectar')

INSERT INTO ALBUM (ID_ALBUM, ARTIST, NAME, TITLE_TRACK)
VALUES(2, 'The Boyz', 'Phantasy Pt. 2', 'Watch it')

INSERT INTO ALBUM (ID_ALBUM, ARTIST, NAME, TITLE_TRACK)
VALUES(3, 'The Boyz', 'Phantasy Pt. 1', 'Lipgloss')

INSERT INTO ALBUM (ID_ALBUM, ARTIST, NAME, TITLE_TRACK)
VALUES(4, 'The Boyz', 'Maverick', 'Maverick')

INSERT INTO ALBUM (ID_ALBUM, ARTIST, NAME, TITLE_TRACK)
VALUES(5, '(G)I-dle', 'Heat', 'I want that')

INSERT INTO ALBUM (ID_ALBUM, ARTIST, NAME, TITLE_TRACK)
VALUES(6, '(G)I-dle', 'I feel', 'Queencard')

INSERT INTO ALBUM (ID_ALBUM, ARTIST, NAME, TITLE_TRACK)
VALUES(7, '(G)I-dle', '2', 'Super lady')

INSERT INTO ALBUM (ID_ALBUM, ARTIST, NAME, TITLE_TRACK)
VALUES(8, 'ZeroBase1', 'You had me at hello', 'Popin')
